on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4

    # Set up the correct Python version for each matrix version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Install pip 
    - name: Install pip
      run: |
        python -m pip install --upgrade pip

    # Install dependencies using pipenv and explicitly specify the Python version
    - name: Install dependencies with pipenv
      run: |
        pip install -r requirements.txt

    # Run pylint within the pipenv environment
    - name: Analyse code with pylint
      run: |
        pylint $(find . -type f -name "*.py" ! -path "./ui/*")

